### ISSUE TITLE
missing ref in documents

### ISSUE THREAD

**Issue by mradamcox** [singerep/censaurus#6]
Reading through the Tutorial, noticed this missing reference:

![image](https://github.com/singerep/censaurus/assets/10427268/a34c92dc-047e-4f9f-bc22-6aa2c4fee597)

`censaurus` looks really good, I look forward to trying it out in the future!

**Comment by singerep** [comment]
Fixed, looks like I meant to delete that at some point!

Thanks for the feedback!
